apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Release.Name }}-{{ .Values.authserver.name }}-service
  name: {{ .Release.Name }}-{{ .Values.authserver.name }}-service
spec:
  type: {{ .Values.authserver.service.type }}
  ports:
  - port: {{ .Values.authserver.service.exposePort }}
    protocol: TCP
    targetPort: {{ .Values.authserver.containerPort }}
  selector:
    app.kubernetes.io/name: {{ .Values.authserver.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.authserver.name }}

status:
  loadBalancer: {}
