{{- if .Values.ingress.enabled -}}
{{- $fullName := include "V1Helm.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName | lower}}
  labels:
    app.kubernetes.io/name: {{ include "V1Helm.name" . }}
    helm.sh/chart: {{ include "V1Helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host.name | quote }}
      http:
        port: {{ .host.port }}
        paths:
	{{- range $ingressPaths }}
          - path: {{ .path.route }}
            backend:
              serviceName: {{ .path.serviceName }}
              servicePort: {{ .path.servicePort }}
	{{- end }}
  {{- end }}
{{- end }}
