apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: encrypt-microservice
spec:
  acme:
    email: sydney900@hotmail.com
    http01: {}
    privateKeySecretRef:
      key: ""
      name: encrypt-microservice
    server: https://localhost