apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Release.Name }}-{{ .Values.apigateway.name }}-service
  name: {{ .Release.Name }}-{{ .Values.apigateway.name }}-service
spec:
  type: loadBalancer
  ports:
  - port: {{ .Values.apigateway.exposePort }}
    protocol: TCP
    targetPort: {{ .Values.apigateway.containerPort }}
  selector:
    run: {{ .Release.Name }}-{{ .Values.apigateway.name }}
status:
  loadBalancer: {}
