apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Release.Name }}-{{ .Values.authserver.name }}-service
  name: {{ .Release.Name }}-{{ .Values.authserver.name }}-service
spec:
  ports:
  - port: {{ .Values.authserver.exposePort }}
    protocol: TCP
    targetPort: {{ .Values.authserver.containerPort }}
  selector:
    run: {{ .Release.Name }}-{{ .Values.authserver.name }}
status:
  loadBalancer: {}
