version: '3.0'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "80"

  clientservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "80"

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "80"
