apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigateway
  labels:
    service: apigateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: apigateway
    spec:
      containers:
      - image: apigateway
        name: apigateway
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
