apiVersion: v1
kind: Service
metadata:
  labels:
    service: clientservice
  name: clientservice
spec:
  ports:
  - name: "64001"
    port: 64001
    targetPort: 80
  selector:
    service: clientservice
status:
  loadBalancer: {}
