apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    service: kafka
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: kafka
status:
  loadBalancer: {}
