apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim0
  labels:
    service: kafka-claim0

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
