apiVersion: v1
kind: Service
metadata:
  name: productservice
  labels:
    service: productservice
spec:
  ports:
  - name: "64002"
    port: 64002
    targetPort: 80
  selector:
    service: productservice
status:
  loadBalancer: {}
