apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    service: zookeeper
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
      - image: wurstmeister/zookeeper:3.4.6
        name: zookeeper
        ports:
        - containerPort: 2181
        resources: {}
      restartPolicy: Always
status: {}
